server:
  port: 15000

spring:
  application:
    name: book-search

#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/homework?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  elasticsearch:
    rest:
      uris: http://192.168.0.100:9200